### PR TITLE
[v1.1.1] Updating Packages

### PR DESCRIPTION
**Pull request by arichiv**
I'm going to split runtime and dev dependencies, before I do that figured I could bump version numbers :-)

### CODE REVIEW

**Comment by arichiv** [comment]
Here's the real change: https://github.com/arichiv/gulp-string-replace/pull/1

**Comment by tomaszczechowski** [comment]
Hi Ari,

Please merge these two changes in our PR, I'll merge and publish them together.

**Comment by tomaszczechowski** [comment]
thanks, and pls update README.MD file according to changes.

**Comment by tomaszczechowski** [comment]
thanks for contribution.

**Pull request merged**
